config/routes.rb
      end

      scope module: :data_sets do
        resources :data_sets, controller: :main, only: :index
      end

      scope module: :factoid_types do
        resources :factoid_types, controller: :main, only: :index
      end

      scope module: :story_types do
        resources :story_types, controller: :main, only: :index
      end
    end

    resources :opportunities, only: :index

    resources :work_requests, only: :update

    scope module: :story_types, path: 'story_types/:story_type_id' do
      resources :template, only: :update
    end

    scope module: :work_requests, path: 'work_requests', as: 'work_request_collections' do
      resources :clients, only: [] do
        get :find_by_name, on: :collection, path: 'bla_bla_bla'
      end
    end


    scope module: :work_requests, path: 'work_requests/:id', as: 'work_request_members' do
      resources :multi_task_statuses, only: [] do
        get :all_deleted, on: :collection
      end
    end

    resources :clients, only: :index do
      resources :publications, only: :index do
        resources :publication_tags, path: :tags, as: :tags, only: :index
      end

      resources :client_tags, path: :tags, as: :tags, only: :index
    end

    resources :main_opportunities, only: :index do
      resources :main_opportunity_revenue_types, path: :revenue_types, as: :revenue_types, only: :index
    end

    resources :main_agencies, only: :index do
      resources :main_agency_opportunities, path: :opportunities, as: :opportunities, only: :index
    end

    resources :data_samples, only: :show

    scope module: :scrape_tasks, path: 'scrape_tasks/:scrape_task_id', as: 'scrape_tasks' do
      resources :multi_tasks, only: %i[create destroy]
    end

    resources :multi_tasks, only: [] do
      get :titles, on: :collection
      get :subtasks, on: :member
    end

    scope module: :multi_tasks, path: 'multi_tasks/:multi_task_id', as: 'tasks' do
      resources :statuses, only: :update
    end

    resources :shown_samples, only: :update

    get 'publication_scopes', to: 'publications#scopes'
    get 'all_publications_scope_id', to: 'publications#all_pubs_scope_id'
    get 'all_local_publications_scope_id', to: 'publications#all_local_pubs_scope_id'
    get 'all_statewide_publications_scope_id', to: 'publications#all_statewide_pubs_scope_id'
  end

  resources :schemas, only: :index do
    scope module: :schemas do
      resources :sql_tables, only: %i[index create destroy]
    end
  end

  scope module: :work_requests do
    resources :work_requests, controller: :main, except: :destroy do
      resource :archive, only: :update
      resource :progress_status, only: :update
      resource :sow_cell, only: :update
    end
  end

  scope module: :factoid_requests do
    resources :factoid_requests, controller: :main, except: :destroy do
      resource :progress_status, only: :update
      resources :templates, only: :update
    end
  end

  get 'tasks/:id', to: 'multi_tasks/main#show'
  scope module: :multi_tasks do
    resources :multi_tasks, controller: :main, except: :destroy do
      get  :add_subtask,    on: :collection
      get  :new_subtask,    on: :collection
      post :create_subtask, on: :collection

      resources :progress_statuses, only: [] do
        patch :change,   on: :collection
        post  :comment,  on: :collection
        patch :subtasks, on: :collection
      end

      resources :checklists, only: %i[new create edit update] do
        patch :confirm, on: :member
      end

      resources :receipts, only: :index do
        patch :confirm, on: :collection
      end

      resources :comments, only: %i[new create edit update destroy]

      resources :assignments, only: [] do
        get   :edit,   on: :collection
        patch :update, on: :collection
        get   :cancel, on: :collection
      end

      resources :notes, only: %i[new create edit update] do
        get :cancel_edit, on: :member
      end
    end
  end
  resources :multi_task_tracking_hours, controller: 'multi_tasks/tracking_hours', only: :index

  scope module: :scrape_tasks do
    resources :scrape_tasks, controller: 'main', except: %i[edit destroy] do

      resource :progress_statuses, only: :update

      resource :instruction, only: %i[edit update] do
        get   :cancel_edit
        patch :autosave
      end

      resource :evaluation_doc, only: %i[edit update] do
        get   :cancel_edit
        patch :autosave
      end

      resource :scraper, only: %i[show edit update]
      resource :tags, only: %i[show edit update]
      resource :multi_tasks, only: %i[show edit update]
      resource :data_sets, only: %i[show edit update]
      resource :table_locations, only: %i[show edit update]
      resource :data_samples, only: :show
      resource :git_links, only: %i[show edit update]
    end
  end

  scope module: :data_sets do
    resources :data_sets, controller: 'main', except: %i[new] do
      get :properties, on: :member

      resource :status, only: :update
      resource :sheriff, only: %i[show edit update]
      resource :responsible_editor, only: %i[show edit update]
      resource :scrape_tasks, only: %i[show edit update]
      resource :table_locations, only: %i[show edit update]
    end

  end

  resources :table_locations, only: :new
  resources :data_samples, only: %i[index]

  scope module: :story_types do
    resources :story_types, controller: :main do
      get   :canceling_edit,  on: :member

      resource :data_set,       only: :update
      resource :property_form,  only: :show
      resource :update_section, only: :update

      resources :templates, path: :template, only: %i[show edit update] do
        patch :save, on: :member
      end

      resources :clients, only: [] do
        post    :include, on: :collection
        delete  :exclude, on: :member

        resources :publications, only: [] do
          post   :include, on: :collection
          delete :exclude, on: :member
        end

        resources :tags, only: [] do
          post   :include, on: :collection
          delete :exclude, on: :member
        end

        resources :sections, only: %i[create destroy]
      end

      resources :excepted_publications, only: [] do
        post   :include, on: :collection
        delete :exclude, on: :member
      end

      resources :default_opportunities do
        patch :set,                  on: :collection
        patch :update_opportunities, on: :collection
      end

      resources :opportunities

      resources :progress_statuses, only: [] do
        patch :change, on: :collection
      end

      resources :levels, path: :level, only: [] do
        post   :include, on: :collection
        delete :exclude, on: :member
      end

      resources :frequencies, path: :frequency, only: [] do
        post   :include, on: :collection
        delete :exclude, on: :member
      end

      resources :photo_buckets, path: :photo_bucket, only: [] do
        post   :include, on: :collection
        delete :exclude, on: :member
      end

      resources :developers, only: [] do
        patch   :include, on: :collection
        delete  :exclude, on: :member
      end

      resources :staging_tables, only: %i[show create destroy] do
        post    :attach,         on: :collection
        patch   :sync,           on: :member
        get     :canceling_edit, on: :collection

        resources :columns, controller: :staging_table_columns, only: %i[edit update]
        resources :indices, controller: :staging_table_indices, only: %i[new create destroy]
      end

      resources :codes, only: [] do
        get    :show,   on: :collection
        post   :attach, on: :collection
        put    :reload, on: :collection
      end

      resources :export_configurations, only: :create do
        patch :update_tags, on: :collection
      end

      resources :fact_checking_docs do
        get   :template
        post  :send_to_reviewers_channel
        patch :save, on: :member

        resources :reviewers_feedback, only: %i[new create] do
          patch :confirm, on: :member
        end

        resources :editors_feedback, only: %i[new create] do
          patch :confirm, on: :member
        end
      end

      resources :cron_tabs, only: %i[edit update]

      resources :iterations, controller: :iterations, only: %i[create update] do
        patch :apply, on: :member
        delete :purge, on: :member

        resources :populations, controller: :populations, path: :populate, only: [] do
          post   :execute, on: :collection
          delete :purge,   on: :collection
        end

        resources :samples, only: %i[index show] do
          post   :create_and_gen_auto_feedback, on: :collection
          delete :purge_sampled, on: :collection
        end

        resources :auto_feedback_confirmations, only: [] do
          patch :confirm, on: :member
        end

        resources :creations, only: [] do
          post   :execute,   on: :collection
          delete :purge, on: :collection
        end

        resources :schedules, path: :schedule, only: [] do
          post  :manual,    on: :collection
          post  :backdate,  on: :collection
          post  :auto,      on: :collection
          patch :purge,     on: :collection
          get   :show_form, on: :collection
        end

        resources :exports, path: :export, only: [] do
          post   :execute,                 on: :collection
          delete :remove_exported_stories, on: :collection
          get    :stories,                 on: :collection
        end

        resources :exported_story_types, only: [] do
          get  :show_editor_report,    on: :collection
          get  :show_manager_report,   on: :collection
          post :submit_editor_report,  on: :collection
          post :submit_manager_report, on: :collection
        end
      end

      resource :reminder, only: [] do
        patch :confirm
        patch :disprove

app/controllers/api/multi_tasks/statuses_controller.rb
# frozen_string_literal: true

module Api
  module MultiTasks
    class StatusesController < ApiController
      before_action :find_task
      before_action :find_status

      def index
        render json: Status.multi_task_statuses.map(&:name)
      end

      def update
        render json: { success: @multi_task.update(status: @status) }
      end

      private

      def find_task
        @multi_task = MultiTask.find(params[:multi_task_id])
      end

      def find_status
        @status = Status.find(params[:id])
      end
    end
  end
end

app/controllers/api/multi_tasks_controller.rb
# frozen_string_literal: true

module Api
  class MultiTasksController < Api::ApiController
    def titles
      task_titles = MultiTask.where(creator: params[:creator_id]).map(&:title)

      render json: task_titles
    end

    def subtasks
      task = MultiTask.find(params[:id])

      render json: { subtasks: task.subtasks }
    end
  end
end

app/controllers/api/v1/multi_tasks/main_controller.rb
# frozen_string_literal: true

module Api
  module V1
    module MultiTasks
      class MainController < MultiTasksController
        def index
          render json: (MultiTask.all.map do |multi_task|
            assigned_to = []
            assigned = multi_task.main_assignee
            assistants = multi_task.assistants
            informed = multi_task.notification_to

            if assigned
              assigned_to << {
                employee: assigned.name,
                role: 'assigned',
                status: multi_task.status.name
              }
            end

            assistants.each do |a|
              task_assistant = multi_task.multi_task_assistants.find_by(account: a)

              assigned_to << {
                employee: a.name,
                role: 'assistant',
                status: task_assistant.done? ? 'done' : multi_task.status.name
              }
            end

            informed.each do |i|
              assigned_to << {
                employee: i.name,
                role: 'informed',
                status: multi_task.status.name
              }
            end

            {
              number: multi_task.id,
              created_by: multi_task.creator.name,
              assigned_to: assigned_to,
              name: multi_task.title,
              opportunities: multi_task.agency_opportunity_revenue_types.map { |o| o.opportunity&.name }.compact,
              deadline: multi_task.deadline,
              main_task_id: multi_task.parent&.id,
              created_at: multi_task.created_at.utc
            }
          end)
        end
      end
    end
  end
end

app/controllers/api/v1/multi_tasks_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class MultiTasksController < ApiController
      private

      def find_multi_task
        @multi_task = ScrapeTask.find(params[:multi_task_id] || params[:id])
      end
    end
  end
end

app/controllers/multi_tasks/assignments_controller.rb
# frozen_string_literal: true

module MultiTasks
  class AssignmentsController < MultiTasksController
    before_action :find_multi_task

    def edit; end

    def update
      return if assistants_params.blank? && assignment_to_params.blank? && notification_to_params.blank?

      new_assignments = new_assignments(@multi_task, Account.find(assistants_params + [assignment_to_params]), notification_to_params)
      update_assignments(@multi_task, new_assignments, assignment_to_params)
      update_notification_to(@multi_task, notification_to_params)
      send_notification(new_assignments)
      comment(new_assignments)
    end

    def cancel; end

    private

    def find_status
      @status = Status.find(params[:status_id])
    end

    def new_assignments(task, assignments, notification_to)
      old_assignments = MultiTaskAssignment.where(multi_task: task, account: (task.assignment_to - assignments))
      old_assignments.destroy_all unless old_assignments.empty?

      old_notification = MultiTaskAssignment.where(multi_task: task, account: (task.notification_to - notification_to), notification_to: 1)
      old_notification.destroy_all unless old_notification.empty?

      assignments - task.assignment_to
    end

    def update_assignments(task, new_assignments, new_main_assignee_id)
      task.assistants << new_assignments

      return if new_main_assignee_id.blank?

      new_main_assignee = Account.find(new_main_assignee_id)
      unless new_main_assignee == task.main_assignee
        old_main_assignee = MultiTaskAssignment.find_by(multi_task: task, main: true)
        old_main_assignee.update(main: false) unless old_main_assignee.blank?
        MultiTaskAssignment.find_by(multi_task: task, account: new_main_assignee).update(main: true)
      end
    end

    def update_notification_to(task, notification_to)
      task.notification_to.destroy_all && return if notification_to.empty?

      Account.find(notification_to).each do |account|
        next if MultiTaskAssignment.find_by(multi_task: task, account: account)

        MultiTaskAssignment.create(multi_task: task, account: account, notification_to: true)
      end
    end

    def comment(new_assignments)
      return if new_assignments.empty?

      @comment = @multi_task.comments.build(
        subtype: 'task comment',
        body: "MultiTask assignment to #{new_assignments.map(&:name).to_sentence}.",
        commentator: current_account
      )
      @comment.save!
    end

    def send_notification(assignments)
      assignments.each do |assignment|
        next if assignment.slack.nil? || assignment.slack.deleted

        message = "*<#{multi_task_url(@multi_task)}| TASK ##{@multi_task.id}> | "\
                  "Assignment to you*\n>#{@multi_task.title}"
        ::SlackNotificationJob.perform_async(assignment.slack.identifier, message)
        ::SlackNotificationJob.perform_async('hle_lokic_task_reminders', message)
      end
    end

    def assignment_to_params
      params[:assignment_to].present? ? params.require(:assignment_to) : nil
    end

    def assistants_params
      params[:assistants].present? ? params.require(:assistants) : []
    end

    def notification_to_params
      params[:notification_to].present? ? params.require(:notification_to) : []
    end
  end
end

app/controllers/multi_tasks/checklists_controller.rb
# frozen_string_literal: true

module MultiTasks
  class ChecklistsController < MultiTasksController
    before_action :find_multi_task
    before_action :find_task_checklist, only: :confirm

    def new; end

    def create
      task_checklists = @multi_task.checklists
      checklists[:descriptions].each { |description| task_checklists.build(description: description).save! }
    end

    def edit; end

    def confirm
      @multi_task_checklist.update!(confirmed: params[:confirm])
    end

    private

    def find_task
      @multi_task = MultiTask.find(params[:multi_task_id])
    end

    def find_task_checklist
      @multi_task_checklist = MultiTaskChecklist.find(params[:id])
    end

    def checklists
      params.require(:checklists).permit(descriptions: [])
    end
  end
end

app/controllers/multi_tasks/receipts_controller.rb
# frozen_string_literal: true

module MultiTasks
  class ReceiptsController < MultiTasksController
    before_action :find_multi_task
    before_action :find_task_assignment

    def confirm
      @multi_task_assignment.update(confirmed: params[:confirmed], confirmed_at: Time.now)
      @multi_task_assignments = @multi_task.assignments
    end

    private

    def find_task_assignment
      @multi_task_assignment = @multi_task.current_assignment(current_account)
    end

    def find_task
      @multi_task = MultiTask.find(params[:multi_task_id])
    end
  end
end

app/helpers/multi_tasks/main_helper.rb
module MultiTasks::MainHelper
end

app/helpers/multi_tasks_helper.rb
module MultiTasksHelper
end

app/views/multi_tasks/comments/_comment.html.haml
%div{ id: "comment_#{comment.id}"}
  .row.small.mr-1
    .col-5.mb-1
      -unless comment.commentator.nil?
        .font-weight-bold
          =comment.commentator.name
    .col-5
      .text-secondary.font-italic.small.mt-1.text-left
        =comment.created_at.strftime('%F %R %Z')
    .col-2
      -if comment.subtype.eql?('user comment') && comment.commentator.eql?(current_account)
        .dropdown
          %span.font-weight-bold{"data-toggle" => "dropdown", :type => "button"} ...
          %ul.dropdown-menu
            -if current_account_permissions('multi_tasks', %w[comments edit_form])
              %li
                =link_to 'edit', edit_multi_task_comment_path(@multi_task, comment), remote: true, class: 'dropdown-item'
            -if current_account_permissions('multi_tasks', %w[comments delete])
              %li
                =link_to 'delete', multi_task_comment_path(@multi_task, comment), method: :delete, remote: true, class: 'dropdown-item', data: { confirm: 'Are you sure you want to delete this comment?' }
  .row.small.col-12.d-block
    =comment.body&.html_safe
  -if comment.assignment?
    .row.text-secondary.font-italic.small.text-left.col-12.blockquote-footer.mt-2
      ='sent to ' + comment.assignment_to_s
    %hr.mt-1.mb-3/
  -else
    %hr.mt-3.mb-3/

app/views/multi_tasks/comments/_edit_form.html.haml
=form_with(url: multi_task_comment_path(@multi_task, @comment), method: :patch) do |form|
  .row
    .col.small
      =form.rich_text_area :body, class: 'form-control overflow-auto', style: 'min-height: 150px;', id: "commentBody_#{@comment.id}"
  .modal-footer.justify-content-center
    .btn.btn-sm.btn-outline-secondary{ "aria-label" => "Close", "data-dismiss" => "modal", type: "button" }
      cancel
    =form.submit :update, class: 'btn btn-sm btn-outline-success'

app/views/multi_tasks/comments/_form.html.haml
=form_with(model: @comment, url: multi_task_comments_path) do |form|
  .row
    .col.small
      =hidden_field_tag 'comment[subtype]', params[:subtype]
      =form.rich_text_area :body, class: 'form-control overflow-auto', required: true, style: 'min-height: 150px;'
  .d-flex.small.font-weight-bold.mt-2.mb-2
    .col-2
      send to:
      =icon('fa', 'plus', class: 'ml-2', id: 'add_assignment_comment')
      .text-secondary.font-italic.small
        (by default send to all)
    .col-10.justify-content-start
      #assignments_comment_form.row
  .modal-footer.justify-content-center
    .btn.btn-sm.btn-outline-secondary{ "aria-label" => "Close", "data-dismiss" => "modal", type: "button" }
      cancel
    =form.submit :send, class: 'btn btn-sm btn-outline-success'

:javascript
  var accounts = #{ raw accounts_for_assignment };

  $('#add_assignment_comment').click(function () {
    let hex = secureRandom(6);

    $('#assignments_comment_form').append(
        `<div id="assignment_${hex}" class="d-flex col-3 mt-2" >
           <select id="comment[assignment_to][]" style = "width:130px" class="mr-1" name="comment[assignment_to][]">${buildSelect(accounts)}</select>
           <div class="ml-1" id="rm_assignment_${hex}" onclick="removeDate(this)"><i class="fa fa-minus"></i></div>
         </div>`
    );
  });

  $('#delete_assignment').click(function () {
    let assignments = document.getElementById('assignments')
    assignments.removeChild(assignments.lastChild)
  });

  function buildSelect(options) {
    var $select = $('');
    for (var i = 0; i < options.length; i++) {
      $select += ('<option value="' + options[i][1] + '">' + options[i][0] + '</option>');
    }
    return $select;
  }

  function removeDate(elem) {
    $(elem.parentNode).remove();
  }

  function secureRandom(n){
    let result = '';
    while (n--){
      result += Math.floor(Math.random() * 16).toString(16);
    }
    return result;
  }

app/views/multi_tasks/comments/create.js.erb
$('#comments').prepend(`<%= j render 'multi_tasks/comments/comment', comment: @comment %>`);
$('#comment').modal('hide');

app/views/multi_tasks/comments/destroy.js.erb
$("#comment_<%= @comment.id %>").remove();

app/views/multi_tasks/comments/edit.js.erb
$('#comment .modal-body').html('<%= j render 'edit_form' %>');
$("#commentBody_<%= @comment.id %>").val(`<%= @comment.body&.html_safe %>`);
$('#comment').modal('show');

app/views/multi_tasks/comments/new.js.erb
$('#comment .modal-body').html('<%= j render 'form' %>');
$('#comment').modal('show');

app/views/multi_tasks/comments/update.js.erb
$("#comment_<%= @comment.id %>").html('<%= j render 'multi_tasks/comments/comment', comment: @comment %>');
$('#comment').modal('hide');