config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#index'

  mount ActionCable.server, at: '/cable'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Sidekiq::Web => '/sidekiq'

  # create/destroy user session
  get    'sign_in',  to: 'authenticates/sessions#new'
  post   'sign_in',  to: 'authenticates/sessions#create'
  delete 'sign_out', to: 'authenticates/sessions#destroy'

  # reset user password
  get   'send_password_reset_email', to: 'authenticates/passwords#new'
  post  'send_password_reset_email', to: 'authenticates/passwords#create'
  get   'password_reset',            to: 'authenticates/passwords#edit'
  patch 'password_reset',            to: 'authenticates/passwords#update'

  # edit user profile
  get   'profile', to: 'authenticates/registrations#edit'
  patch 'profile', to: 'authenticates/registrations#update'

  scope module: :accounts do
    resources :accounts, controller: :main, except: :destroy do
      resource  :status, only: :update
      resource  :roles, only: %i[show edit update]
      resources :cards, only: %i[create update destroy] do
        scope module: :cards do
          resources :access_levels, only: %i[show new create edit update]
        end
      end
    end
  end

  post   'accounts/:account_id/impersonate', to: 'accounts/impersonates#create', as: 'account_impersonate'
  delete 'accounts/stop_impersonating',      to: 'accounts/impersonates#destroy', as: 'account_stop_impersonating'

  namespace :api, constraints: { format: :json } do
    namespace :v1 do
      scope module: :multi_tasks do
        resources :multi_tasks, controller: :main, only: %i[index]
      end

      scope module: :scrape_tasks do
        resources :scrape_tasks, controller: :main, only: %i[index show]
      end

      scope module: :data_sets do
        resources :data_sets, controller: :main, only: :index
      end

      scope module: :factoid_types do
        resources :factoid_types, controller: :main, only: :index
      end

      scope module: :story_types do
        resources :story_types, controller: :main, only: :index
      end
    end

    resources :opportunities, only: :index

    resources :work_requests, only: :update

    scope module: :story_types, path: 'story_types/:story_type_id' do
      resources :template, only: :update
    end

    scope module: :work_requests, path: 'work_requests', as: 'work_request_collections' do
      resources :clients, only: [] do
        get :find_by_name, on: :collection, path: 'bla_bla_bla'
      end
    end


    scope module: :work_requests, path: 'work_requests/:id', as: 'work_request_members' do
      resources :multi_task_statuses, only: [] do
        get :all_deleted, on: :collection
      end
    end

    resources :clients, only: :index do
      resources :publications, only: :index do
        resources :publication_tags, path: :tags, as: :tags, only: :index
      end

      resources :client_tags, path: :tags, as: :tags, only: :index
    end

    resources :main_opportunities, only: :index do
      resources :main_opportunity_revenue_types, path: :revenue_types, as: :revenue_types, only: :index
    end

    resources :main_agencies, only: :index do
      resources :main_agency_opportunities, path: :opportunities, as: :opportunities, only: :index
    end

    resources :data_samples, only: :show

    scope module: :scrape_tasks, path: 'scrape_tasks/:scrape_task_id', as: 'scrape_tasks' do
      resources :multi_tasks, only: %i[create destroy]
    end

    resources :multi_tasks, only: [] do
      get :titles, on: :collection
      get :subtasks, on: :member
    end

    scope module: :multi_tasks, path: 'multi_tasks/:multi_task_id', as: 'tasks' do
      resources :statuses, only: :update
    end

    resources :shown_samples, only: :update

    get 'publication_scopes', to: 'publications#scopes'
    get 'all_publications_scope_id', to: 'publications#all_pubs_scope_id'
    get 'all_local_publications_scope_id', to: 'publications#all_local_pubs_scope_id'
    get 'all_statewide_publications_scope_id', to: 'publications#all_statewide_pubs_scope_id'
  end

  resources :schemas, only: :index do
    scope module: :schemas do
      resources :sql_tables, only: %i[index create destroy]
    end
  end

  scope module: :work_requests do
    resources :work_requests, controller: :main, except: :destroy do
      resource :archive, only: :update
      resource :progress_status, only: :update
      resource :sow_cell, only: :update
    end
  end

  scope module: :factoid_requests do
    resources :factoid_requests, controller: :main, except: :destroy do
      resource :progress_status, only: :update
      resources :templates, only: :update
    end
  end

  get 'tasks/:id', to: 'multi_tasks/main#show'
  scope module: :multi_tasks do
    resources :multi_tasks, controller: :main, except: :destroy do
      get  :add_subtask,    on: :collection
      get  :new_subtask,    on: :collection
      post :create_subtask, on: :collection

      resources :progress_statuses, only: [] do
        patch :change,   on: :collection
        post  :comment,  on: :collection
        patch :subtasks, on: :collection
      end

      resources :checklists, only: %i[new create edit update] do
        patch :confirm, on: :member
      end

      resources :receipts, only: :index do
        patch :confirm, on: :collection
      end

      resources :comments, only: %i[new create edit update destroy]

      resources :assignments, only: [] do
        get   :edit,   on: :collection
        patch :update, on: :collection
        get   :cancel, on: :collection
      end

      resources :notes, only: %i[new create edit update] do
        get :cancel_edit, on: :member
      end
    end
  end
  resources :multi_task_tracking_hours, controller: 'multi_tasks/tracking_hours', only: :index

  scope module: :scrape_tasks do
    resources :scrape_tasks, controller: 'main', except: %i[edit destroy] do

      resource :progress_statuses, only: :update

      resource :instruction, only: %i[edit update] do
        get   :cancel_edit
        patch :autosave
      end

      resource :evaluation_doc, only: %i[edit update] do
        get   :cancel_edit
        patch :autosave
      end

      resource :scraper, only: %i[show edit update]
      resource :tags, only: %i[show edit update]
      resource :multi_tasks, only: %i[show edit update]
      resource :data_sets, only: %i[show edit update]
      resource :table_locations, only: %i[show edit update]
      resource :data_samples, only: :show
      resource :git_links, only: %i[show edit update]
    end
  end

  scope module: :data_sets do
    resources :data_sets, controller: 'main', except: %i[new] do
      get :properties, on: :member

      resource :status, only: :update
      resource :sheriff, only: %i[show edit update]
      resource :responsible_editor, only: %i[show edit update]
      resource :scrape_tasks, only: %i[show edit update]
      resource :table_locations, only: %i[show edit update]
    end

  end

  resources :table_locations, only: :new
  resources :data_samples, only: %i[index]

  scope module: :story_types do
    resources :story_types, controller: :main do
      get   :canceling_edit,  on: :member

      resource :data_set,       only: :update
      resource :property_form,  only: :show
      resource :update_section, only: :update

      resources :templates, path: :template, only: %i[show edit update] do
        patch :save, on: :member
      end

      resources :clients, only: [] do
        post    :include, on: :collection
        delete  :exclude, on: :member

        resources :publications, only: [] do
          post   :include, on: :collection
          delete :exclude, on: :member
        end

        resources :tags, only: [] do
          post   :include, on: :collection
          delete :exclude, on: :member
        end

        resources :sections, only: %i[create destroy]
      end

      resources :excepted_publications, only: [] do
        post   :include, on: :collection
        delete :exclude, on: :member
      end

      resources :default_opportunities do
        patch :set,                  on: :collection
        patch :update_opportunities, on: :collection
      end

      resources :opportunities

      resources :progress_statuses, only: [] do
        patch :change, on: :collection
      end

      resources :levels, path: :level, only: [] do
        post   :include, on: :collection
        delete :exclude, on: :member
      end

      resources :frequencies, path: :frequency, only: [] do
        post   :include, on: :collection
        delete :exclude, on: :member
      end

      resources :photo_buckets, path: :photo_bucket, only: [] do
        post   :include, on: :collection
        delete :exclude, on: :member
      end

      resources :developers, only: [] do
        patch   :include, on: :collection
        delete  :exclude, on: :member
      end

      resources :staging_tables, only: %i[show create destroy] do
        post    :attach,         on: :collection
        patch   :sync,           on: :member
        get     :canceling_edit, on: :collection

        resources :columns, controller: :staging_table_columns, only: %i[edit update]
        resources :indices, controller: :staging_table_indices, only: %i[new create destroy]
      end

      resources :codes, only: [] do
        get    :show,   on: :collection
        post   :attach, on: :collection
        put    :reload, on: :collection
      end

      resources :export_configurations, only: :create do
        patch :update_tags, on: :collection
      end

      resources :fact_checking_docs do
        get   :template
        post  :send_to_reviewers_channel
        patch :save, on: :member

        resources :reviewers_feedback, only: %i[new create] do
          patch :confirm, on: :member
        end

        resources :editors_feedback, only: %i[new create] do

app/controllers/api/v1/data_sets/main_controller.rb
# frozen_string_literal: true

module Api
  module V1
    module DataSets
      class MainController < DataSetsController
        def index
          render json: DataSet.all.map(&:name) if params[:names]
        end
      end
    end
  end
end

app/controllers/api/v1/data_sets_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class DataSetsController < ApiController
      private

      def find_data_set
        @data_set = DataSet.find(params[:data_set_id] || params[:id])
      end
    end
  end
end

app/controllers/api/v1/scrape_tasks/main_controller.rb
# frozen_string_literal: true

module Api
  module V1
    module ScrapeTasks
      class MainController < ScrapeTasksController
        before_action :find_scrape_task, only: :show

        def index
          if params[:names]
            render json: ScrapeTask.all.map(&:name)
          else
            html_sanitizer = ActionView::Base.full_sanitizer

            render json: (ScrapeTask.all.map do |scrape_task|
              {
                number: scrape_task.id,
                created_by: scrape_task.creator&.name,
                scraper: scrape_task.scraper&.name,
                status: scrape_task.status.name,
                tags: scrape_task.tags.map(&:name),
                has_data_location: scrape_task.table_locations.present?,
                name: scrape_task.name,
                frequency: scrape_task.frequency&.name,
                deadline: scrape_task.deadline,
                general_comment: html_sanitizer.sanitize(scrape_task.general_comment&.body),
                created_at: scrape_task.created_at.utc
              }
            end)
          end
        end

        def show
          html_sanitizer = ActionView::Base.full_sanitizer

          render json: {
            status: @scrape_task.status.name,
            created_by: @scrape_task.creator.name,
            created_at: @scrape_task.created_at.utc,
            updated_at: @scrape_task.updated_at.utc,
            main_info: {
              tags: @scrape_task.tags.map(&:name),
              name: @scrape_task.name,
              multi_tasks: @scrape_task.multi_tasks.pluck(:id),
              gather_task_id: @scrape_task.gather_task,
              deadline: @scrape_task.deadline,
              state: @scrape_task.state&.name,
              URL: @scrape_task.datasource_url,
              comment_on_datasource: html_sanitizer.sanitize(@scrape_task.datasource_comment&.body),
              scrapable: @scrape_task.scrapable.eql?(-1) ? nil : @scrape_task.scrapable.eql?(1),
              comment_on_scrape_ability: html_sanitizer.sanitize(@scrape_task.scrape_ability_comment&.body),
              scraper: @scrape_task.scraper&.name,
              frequency: @scrape_task.frequency&.name,
              general_comment: html_sanitizer.sanitize(@scrape_task.general_comment&.body),
              table_locations: @scrape_task.table_locations.map(&:full_name),
              data_sets: [@scrape_task.data_set&.id]
            },
            instruction: @scrape_task.instruction&.body,
            evaluation_document: @scrape_task.evaluation_doc&.body
          }
        end
      end
    end
  end
end

app/controllers/api/v1/scrape_tasks_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ScrapeTasksController < ApiController
      private

      def find_scrape_task
        @scrape_task = ScrapeTask.find(params[:scrape_task_id] || params[:id])
      end
    end
  end
end

app/controllers/data_sets/responsible_editors_controller.rb
# frozen_string_literal: true

module DataSets
  class ResponsibleEditorsController < DataSetsController
    before_action :find_data_set
    before_action :find_responsible_editor, only: :update

    def show; end

    def edit
      @responsible_editors = AccountRole.find_by(name: 'Content Manager').accounts.ordered
    end

    def update
      if @responsible_editor.nil? || @responsible_editor.roles.find_by(name: 'Content Manager')
        @data_set.update(responsible_editor: @responsible_editor)
      else
        flash.now[:error] = { responsible_editor: :error }
      end

      render 'data_sets/responsible_editors/show'
    end

    private

    def find_responsible_editor
      @responsible_editor = Account.find_by(id: params[:responsible_editor][:id])
    end
  end
end

app/controllers/data_sets/scrape_tasks_controller.rb
# frozen_string_literal: true

module DataSets
  class ScrapeTasksController < DataSetsController
    before_action :find_data_set

    def show; end

    def edit; end

    def update
      @data_set.scrape_tasks.clear

      scrape_tasks_params.keep_if { |_k, v| v.eql?('1') }.keys.each do |ds|
        @data_set.scrape_tasks << ScrapeTask.find(ds)
      end

      render 'data_sets/scrape_tasks/show'
    end

    private

    def scrape_tasks_params
      params[:scrape_tasks] ? params.require(:scrape_tasks).permit!.to_h : {}
    end
  end
end

app/controllers/data_sets/sheriffs_controller.rb
# frozen_string_literal: true

module DataSets
  class SheriffsController < DataSetsController
    before_action :find_data_set
    before_action :find_sheriff, only: :update

    def show; end

    def edit
      @sheriffs = AccountRole.find_by(name: 'Content Data Cleaner').accounts.ordered
    end

    def update
      if @sheriff.nil? || @sheriff.roles.find_by(name: 'Content Data Cleaner')
        @data_set.update(sheriff: @sheriff)
      else
        flash.now[:error] = { sheriff: :error }
      end

      render 'data_sets/sheriffs/show'
    end

    private

    def find_sheriff
      @sheriff = Account.find_by(id: params[:sheriff][:id])
    end
  end
end

app/controllers/data_sets/statuses_controller.rb
# frozen_string_literal: true

module DataSets
  class StatusesController < DataSetsController
    before_action :find_data_set
    before_action :find_status

    def update
      @data_set.update(status: @status)
      return unless params[:reasons]

      @data_set.status_comment.update(body: params[:reasons])
    end

    private

    def find_status
      @status = Status.find(params[:status_id])
    end
  end
end

app/controllers/data_sets/table_locations_controller.rb
# frozen_string_literal: true

module DataSets
  class TableLocationsController < DataSetsController
    before_action :find_data_set

    def show; end

    def edit; end

    def update
      @data_set.table_locations.clear

      table_locations_params.each do |key, value|
        next if value.eql?('0')

        host_id, schema_id, sql_table_id = key.split('_')
        @data_set.table_locations.create(
          host: Host.find(host_id),
          schema: Schema.find(schema_id),
          sql_table: SqlTable.find(sql_table_id)
        )
      end

      render 'data_sets/table_locations/show'
    end

    private

    def table_locations_params
      params[:table_locations] ? params.require(:table_locations).permit!.to_h : {}
    end
  end
end

app/controllers/data_sets_controller.rb
# frozen_string_literal: true

class DataSetsController < ApplicationController # :nodoc:
  before_action -> { authorize!('data_sets') }
  before_action -> { authorize!('story_types', redirect: false) }
  before_action -> { authorize!('factoid_types', redirect: false) }

  private

  def find_data_set
    @data_set = DataSet.find(params[:data_set_id] || params[:id])
  end

  def find_status_comment
    @status_comment = @data_set.status_comment || @data_set.create_status_comment
  end
end

app/views/scrape_tasks/data_sets/_data_sets.html.erb
<div id="dataSets" class="row mb-3">
  <div class="col-3 text-right pr-0">
    <b>DATA SETS:</b>
    <% if current_account_permissions('scrape_tasks', %w[data_sets edit_form]) %>
      <%= link_to(icon('fa', 'pencil-square'), edit_scrape_task_data_sets_path(@scrape_task), class: 'p-0 ml-2', remote: true) %>
    <% end %>
  </div>

  <div class="col">
    <% @scrape_task.data_sets.each do |ds| %>
      <%= link_to("##{ds.id} #{ds.name}", data_set_path(ds), target: '_blank') %>
      <br/>
    <% end %>
  </div>
</div>

app/views/scrape_tasks/data_sets/_form.html.erb
<hr class="mt-0">

<%= form_with(url: scrape_task_data_sets_path(@scrape_task), method: :patch, html: { class: 'ml-3',  onkeypress: "return event.keyCode !== 13;" } ) do |f| %>
  <div class="form-group form-check mb-0">
    <% @scrape_task.data_sets.each do |ds| %>
      <%= f.check_box "data_sets[#{ds.id}]", class: 'form-check-input', checked: true  %>
      <%= f.label "data_sets[#{ds.id}]", "##{ds.id} #{ds.name}", class: 'form-check-label' %>
      <br/>
    <% end %>
  </div>

  <div id="dataSetsInputBlock" class="d-flex mb-2">
    <span>ADD: </span>
    <div class="form-group mb-0">
      <input class="underline-input pt-0" list='dataSetsDataList'>
      <datalist id="dataSetsDataList">
        <% DataSet.all.each do |ds| %>
          <option value="<%= "##{ds.id} #{ds.name}" %>"></option>
        <% end %>
      </datalist>

      <span class="mr-2 ml-2">OR</span>
      <%= link_to('[ create ]', '#', "data-toggle" => "modal", "data-target" => "#createDataSetModal") %>

      <div class="small"> *** press enter </div>
    </div>
  </div>

  <%= f.submit '[ save ]', class: 'btn btn-sm btn-link p-0' %>
  <%= link_to('[ cancel ]', scrape_task_data_sets_path, class: 'btn btn-sm btn-link text-secondary p-0', remote: true) %>
<% end %>

<hr class="mb-0">

<div id="createDataSetModal" class="modal fade" aria-hidden="true" aria-labelledby="createDataSetModal"
     role="dialog" tabindex="-1" data-backdrop="static" data-keyboard='false'>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        NEW DATA SET
        <button class="close" aria-label="Close" data-dismiss="modal" type="button">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <%=render 'scrape_tasks/data_sets/new' %>
      </div>
      <div class="modal-footer justify-content-center">
        <%= link_to('CREATE', '#', id: 'createDataSetButton', class: 'btn btn-sm btn-dark') %>
        <div class="btn btn-sm btn-outline-secondary" aria-label="Close" data-dismiss="modal" type=button">CANCEL</div>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript" charset="utf-8">
    document.querySelector('#createDataSetButton').addEventListener('click', (event) => {
        event.preventDefault();
        document.querySelector('#hiddenCreateDataSetButton').click();
    }, false);
</script>

<%= javascript_pack_tag 'scrape_tasks/data_sets/form' %>

app/views/scrape_tasks/data_sets/_new.html.haml
=form_with(url: data_sets_path, local: true, html: { onkeypress: "return event.keyCode !== 13;" } ) do |f|
  #nameAnchor.mb-1
  #name
    .row
      .col-10.offset-1
        .font-weight-bold.mb-2
          NAME:
          %span.small.text-danger
            *required
        =f.text_field "data_set[name]", class: 'form-control form-control-sm', value: @scrape_task&.name
        #newDataSetNameExist.text-danger.d-none
          Data Set with this name already exists. Let's use something else
  =f.submit 'Submit', id: 'hiddenCreateDataSetButton', class: 'd-none'

:javascript
  document.querySelector('#name input').addEventListener('input', () => {
    document.querySelector('#newDataSetNameExist').classList.add('d-none');
  });

  function isUniq(name, names) {
    let lowName = name.toLowerCase();
    return !names.find(el => lowName === el.toLowerCase());
  }

  document.querySelector('#createDataSetModal form').addEventListener('submit', onSubmit);

  function onSubmit(event) {
    event.preventDefault();
    event.stopPropagation();

    let name = document.querySelector('#name input').value;
    if(name.length === 0) {
      scrollToCard('#createDataSetModal .modal-body')
      return false;
    } else {
      Rails.ajax({
        type: 'GET',
        dataType: 'json',
        url: `/api/v1/data_sets?names=true`,
        success: (names) => {
          let nameIsUniq = isUniq(name, names)

          if(nameIsUniq === true) {
            Rails.ajax({
              type: 'POST',
              dataType: 'script',
              url: `/data_sets`,
              data: `data_set[name]=${encodeURIComponent(name.trim())}&data_set[scrape_task_id]=#{@scrape_task.id}`
            });
          } else {
            document.querySelector('#newDataSetNameExist').classList.remove('d-none');
          }
        }
      });
    }
  }

  function scrollToCard(id) {
    let required = document.querySelector(id);

    required.addEventListener('animationend', (ev) => { ev.target.classList.remove('touch-required-field') });
    document.querySelector(id).classList.add('border-danger', 'touch-required-field');
    document.querySelector(`${id}Anchor`).scrollIntoView();
  }

app/views/scrape_tasks/data_sets/edit.js.erb
$('#dataSets>:first-child>a').addClass('disabled-link');
$('#dataSets>.col').html('<%= j render 'scrape_tasks/data_sets/form' %>');

app/views/scrape_tasks/data_sets/show.js.erb
$('#dataSets>.col').html(
    '<%= @scrape_task.data_sets.map { |ds| link_to("##{ds.id} #{ds.name}", data_set_path(ds), target: '_blank') }.join('<br>').html_safe %>'
);
$('#dataSets>:first-child>a').removeClass('disabled-link');