config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#index'

  mount ActionCable.server, at: '/cable'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Sidekiq::Web => '/sidekiq'

  # create/destroy user session
  get    'sign_in',  to: 'authenticates/sessions#new'
  post   'sign_in',  to: 'authenticates/sessions#create'
  delete 'sign_out', to: 'authenticates/sessions#destroy'

  # reset user password
  get   'send_password_reset_email', to: 'authenticates/passwords#new'
  post  'send_password_reset_email', to: 'authenticates/passwords#create'
  get   'password_reset',            to: 'authenticates/passwords#edit'
  patch 'password_reset',            to: 'authenticates/passwords#update'

  # edit user profile
  get   'profile', to: 'authenticates/registrations#edit'
  patch 'profile', to: 'authenticates/registrations#update'

  scope module: :accounts do
    resources :accounts, controller: :main, except: :destroy do
      resource  :status, only: :update
      resource  :roles, only: %i[show edit update]
      resources :cards, only: %i[create update destroy] do
        scope module: :cards do
          resources :access_levels, only: %i[show new create edit update]
        end
      end
    end
  end

  post   'accounts/:account_id/impersonate', to: 'accounts/impersonates#create', as: 'account_impersonate'
  delete 'accounts/stop_impersonating',      to: 'accounts/impersonates#destroy', as: 'account_stop_impersonating'

  namespace :api, constraints: { format: :json } do
    namespace :v1 do
      scope module: :multi_tasks do
        resources :multi_tasks, controller: :main, only: %i[index]
      end

      scope module: :scrape_tasks do
        resources :scrape_tasks, controller: :main, only: %i[index show]
      end

      scope module: :data_sets do
        resources :data_sets, controller: :main, only: :index
      end

      scope module: :factoid_types do
        resources :factoid_types, controller: :main, only: :index
      end

      scope module: :story_types do
        resources :story_types, controller: :main, only: :index
      end
    end

    resources :opportunities, only: :index

    resources :work_requests, only: :update

    scope module: :story_types, path: 'story_types/:story_type_id' do
      resources :template, only: :update
    end

    scope module: :work_requests, path: 'work_requests', as: 'work_request_collections' do
      resources :clients, only: [] do
        get :find_by_name, on: :collection, path: 'bla_bla_bla'
      end
    end


    scope module: :work_requests, path: 'work_requests/:id', as: 'work_request_members' do
      resources :multi_task_statuses, only: [] do
        get :all_deleted, on: :collection
      end
    end

    resources :clients, only: :index do
      resources :publications, only: :index do
        resources :publication_tags, path: :tags, as: :tags, only: :index
      end

      resources :client_tags, path: :tags, as: :tags, only: :index
    end

    resources :main_opportunities, only: :index do
      resources :main_opportunity_revenue_types, path: :revenue_types, as: :revenue_types, only: :index
    end

    resources :main_agencies, only: :index do
      resources :main_agency_opportunities, path: :opportunities, as: :opportunities, only: :index
    end

    resources :data_samples, only: :show

    scope module: :scrape_tasks, path: 'scrape_tasks/:scrape_task_id', as: 'scrape_tasks' do
      resources :multi_tasks, only: %i[create destroy]
    end

    resources :multi_tasks, only: [] do
      get :titles, on: :collection
      get :subtasks, on: :member
    end

    scope module: :multi_tasks, path: 'multi_tasks/:multi_task_id', as: 'tasks' do
      resources :statuses, only: :update
    end

    resources :shown_samples, only: :update

    get 'publication_scopes', to: 'publications#scopes'
    get 'all_publications_scope_id', to: 'publications#all_pubs_scope_id'
    get 'all_local_publications_scope_id', to: 'publications#all_local_pubs_scope_id'
    get 'all_statewide_publications_scope_id', to: 'publications#all_statewide_pubs_scope_id'
  end

  resources :schemas, only: :index do
    scope module: :schemas do
      resources :sql_tables, only: %i[index create destroy]
    end
  end

  scope module: :work_requests do
    resources :work_requests, controller: :main, except: :destroy do
      resource :archive, only: :update
      resource :progress_status, only: :update
      resource :sow_cell, only: :update
    end
  end

  scope module: :factoid_requests do
    resources :factoid_requests, controller: :main, except: :destroy do
      resource :progress_status, only: :update
      resources :templates, only: :update
    end
  end

  get 'tasks/:id', to: 'multi_tasks/main#show'
  scope module: :multi_tasks do
    resources :multi_tasks, controller: :main, except: :destroy do
      get  :add_subtask,    on: :collection
      get  :new_subtask,    on: :collection
      post :create_subtask, on: :collection

      resources :progress_statuses, only: [] do
        patch :change,   on: :collection
        post  :comment,  on: :collection
        patch :subtasks, on: :collection
      end

      resources :checklists, only: %i[new create edit update] do
        patch :confirm, on: :member
      end

      resources :receipts, only: :index do
        patch :confirm, on: :collection
      end

      resources :comments, only: %i[new create edit update destroy]

      resources :assignments, only: [] do
        get   :edit,   on: :collection
        patch :update, on: :collection
        get   :cancel, on: :collection
      end

      resources :notes, only: %i[new create edit update] do
        get :cancel_edit, on: :member
      end
    end
  end
  resources :multi_task_tracking_hours, controller: 'multi_tasks/tracking_hours', only: :index

  scope module: :scrape_tasks do
    resources :scrape_tasks, controller: 'main', except: %i[edit destroy] do

      resource :progress_statuses, only: :update

      resource :instruction, only: %i[edit update] do
        get   :cancel_edit
        patch :autosave
      end

      resource :evaluation_doc, only: %i[edit update] do
        get   :cancel_edit
        patch :autosave
      end

      resource :scraper, only: %i[show edit update]
      resource :tags, only: %i[show edit update]
      resource :multi_tasks, only: %i[show edit update]
      resource :data_sets, only: %i[show edit update]
      resource :table_locations, only: %i[show edit update]
      resource :data_samples, only: :show
      resource :git_links, only: %i[show edit update]
    end
  end

  scope module: :data_sets do
    resources :data_sets, controller: 'main', except: %i[new] do
      get :properties, on: :member

      resource :status, only: :update
      resource :sheriff, only: %i[show edit update]
      resource :responsible_editor, only: %i[show edit update]
      resource :scrape_tasks, only: %i[show edit update]
      resource :table_locations, only: %i[show edit update]
    end

  end

  resources :table_locations, only: :new
  resources :data_samples, only: %i[index]

  scope module: :story_types do
    resources :story_types, controller: :main do
      get   :canceling_edit,  on: :member

      resource :data_set,       only: :update
      resource :property_form,  only: :show
      resource :update_section, only: :update

      resources :templates, path: :template, only: %i[show edit update] do
        patch :save, on: :member
      end

      resources :clients, only: [] do
        post    :include, on: :collection
        delete  :exclude, on: :member

        resources :publications, only: [] do
          post   :include, on: :collection
          delete :exclude, on: :member
        end

        resources :tags, only: [] do
          post   :include, on: :collection
          delete :exclude, on: :member
        end

        resources :sections, only: %i[create destroy]
      end

      resources :excepted_publications, only: [] do
        post   :include, on: :collection
        delete :exclude, on: :member
      end

      resources :default_opportunities do
        patch :set,                  on: :collection
        patch :update_opportunities, on: :collection
      end

      resources :opportunities

      resources :progress_statuses, only: [] do
        patch :change, on: :collection
      end

      resources :levels, path: :level, only: [] do
        post   :include, on: :collection
        delete :exclude, on: :member
      end

      resources :frequencies, path: :frequency, only: [] do
        post   :include, on: :collection
        delete :exclude, on: :member
      end

      resources :photo_buckets, path: :photo_bucket, only: [] do
        post   :include, on: :collection
        delete :exclude, on: :member
      end

      resources :developers, only: [] do
        patch   :include, on: :collection
        delete  :exclude, on: :member
      end

      resources :staging_tables, only: %i[show create destroy] do
        post    :attach,         on: :collection
        patch   :sync,           on: :member
        get     :canceling_edit, on: :collection

        resources :columns, controller: :staging_table_columns, only: %i[edit update]
        resources :indices, controller: :staging_table_indices, only: %i[new create destroy]
      end

      resources :codes, only: [] do
        get    :show,   on: :collection
        post   :attach, on: :collection
        put    :reload, on: :collection
      end

      resources :export_configurations, only: :create do
        patch :update_tags, on: :collection
      end

      resources :fact_checking_docs do
        get   :template
        post  :send_to_reviewers_channel
        patch :save, on: :member

        resources :reviewers_feedback, only: %i[new create] do
          patch :confirm, on: :member
        end

        resources :editors_feedback, only: %i[new create] do

app/controllers/api/v1/factoid_types/main_controller.rb
# frozen_string_literal: true

module Api
  module V1
    module FactoidTypes
      class MainController < FactoidTypesController
        def index
          render json: FactoidType.all.map(&:name) if params[:names]
        end
      end
    end
  end
end

app/controllers/api/v1/factoid_types_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class FactoidTypesController < ApiController
      private

      def find_factoid_type
        @factoid_type = FactoidType.find(params[:factoid_type_id] || params[:id])
      end
    end
  end
end

app/controllers/factoid_types/codes_controller.rb
# frozen_string_literal: true

module FactoidTypes
  class CodesController < FactoidTypesController # :nodoc:
    before_action :download_code, only: %i[attach reload]

    def show
      @ruby_code =
        CodeRay.scan(@factoid_type.code.download, :ruby).div(line_numbers: :table)
    end

    def attach
      render_403 && return if @factoid_type.code.attached? || @code.nil?

      @factoid_type.code.attach(io: StringIO.new(@code), filename: "f#{@factoid_type.id}.rb")
    end

    def reload
      render_403 && return if @code.nil?

      @factoid_type.code.purge
      @factoid_type.code.attach(io: StringIO.new(@code), filename: "f#{@factoid_type.id}.rb")
    end

    private

    def download_code
      @code = @factoid_type.download_code_from_db
    end
  end
end

app/controllers/factoid_types/creations_controller.rb
# frozen_string_literal: true

module FactoidTypes
  class CreationsController < FactoidTypesController # :nodoc:
     def execute
      @iteration.update!(creation: false, current_account: current_account)
      CreationJob.perform_async(@iteration.id,current_account.id)
    end

    def purge
      @iteration.update!(purge_creation: true, current_account: current_account)
      PurgeCreationJob.perform_async(@iteration.id,current_account.id)
    end
  end
end

app/controllers/factoid_types/data_sets_controller.rb
# frozen_string_literal: true

module FactoidTypes
  class DataSetsController < FactoidTypesController
    before_action :find_current_data_set

    def update
      @factoid_type.update!(change_data_set_params)
    end

    private

    def change_data_set_params
      attrs = params.require(:factoid_type).permit(:data_set_id)
      attrs[:current_account] = current_account
      attrs
    end

    def find_current_data_set
      data_set_id = params[:current_data_set_page_id].present? ? params[:current_data_set_page_id] : params[:factoid_type][:data_set_id]
      @current_data_set = DataSet.find(data_set_id)
    end
  end
end

app/controllers/factoid_types/developers_controller.rb
# frozen_string_literal: true

module FactoidTypes
  class DevelopersController < FactoidTypesController
    before_action :find_developer, only: :include

    def include
      render_403 && return if @factoid_type.developer

      @factoid_type.update!(developer: @developer, current_account: current_account)
    end

    def exclude
      render_403 && return unless @factoid_type.developer

      @factoid_type.update!(developer: nil, current_account: current_account)
      @content_developers = AccountRole.find_by(name: 'Content Developer').accounts.ordered
    end

    private

    def find_developer
      @developer = @factoid_type.developer || Account.find(params[:id])
    end
  end
end

app/controllers/factoid_types/editors_feedback_controller.rb
# frozen_string_literal: true

module FactoidTypes
  class EditorsFeedbackController < FactoidTypesController
    before_action :find_fcd, only: %i[create confirm]
    before_action :find_feedback_collection, only: %i[create confirm]
    after_action  :send_notification_to_dev, only: :create
    after_action  :send_confirm_to_fc_channel, only: :confirm

    def new; end

    def create
      @feedback = @feedback_collection.build(editors_feedback_params)
      @feedback.editor =current_account
      @feedback.approvable = params[:commit].eql?('approve!')

      if @feedback.save
        redirect_to "#{factoid_type_fact_checking_doc_path(@factoid_type, @fcd)}#editors_feedback"
      else
        flash.now[:message] = ''
      end
    end

    def confirm
      @feedback = @feedback_collection.find(params[:id])
      render_403 and return if @feedback.confirmed

      @feedback.update!(confirmed: true)
    end

    private

    def find_fcd
      @fcd = @factoid_type.fact_checking_doc
    end

    def find_feedback_collection
      @feedback_collection = @fcd.editors_feedback
    end

    def editors_feedback_params
      params.require(:editors_feedback).permit(:body)
    end

    def send_notification_to_dev
      developer_pm = @factoid_type.developer&.slack&.identifier
      return if developer_pm.nil?

      message = "*[ LokiC ] <#{factoid_type_url(@factoid_type)}|Factoid Type ##{@factoid_type.id}> (#{@factoid_type.iteration.name}) | FCD*\n>"

      if params[:commit].eql?('approve!')
        approvable = @fcd.approval_editors
        editors = approvable.map(&:name).join(', ')
        scheduling =
          if approvable.count > 1
            'You can go to create all stories and scheduling'
          else
            'You need one more approval from editors'
          end
        message += "Approved by *#{editors}*. #{scheduling}."
      else
        message += "You received the *editors' feedback* by *#{current_account.name}*. "\
                   "<#{factoid_type_fact_checking_doc_url(@factoid_type, @factoid_type.fact_checking_doc)}"\
                   '#editors_feedback|Check it>.'
      end

      ::SlackNotificationJob.perform_async(developer_pm, message)
    end

    def send_confirm_to_fc_channel
      fact_checking_channel = @factoid_type.developer&.fact_checking_channel&.name
      return unless fact_checking_channel || @feedback_collection.where(approvable: false).all?(&:confirmed)

      message = "*Updated Factoid Type FCD* ##{@factoid_type.id} "\
                "<#{factoid_type_fact_checking_doc_url(@factoid_type, @fcd)}|#{@factoid_type.name}>."

      ::SlackNotificationJob.perform_async(fact_checking_channel, message)
    end
  end
end

app/controllers/factoid_types/exports_controller.rb
# frozen_string_literal: true

module FactoidTypes
  class ExportsController < FactoidTypesController
    before_action :get_factoid_ids, only: :remove_selected_factoids
    before_action :get_factoids, only: [:factoids, :update_section]

    def execute
      @iteration.update!(export: false, current_account: current_account)
      ExportJob.perform_async(@iteration.id, current_account.id, params[:chunk])
    end

    def remove_exported_factoids
      @iteration.update!(purge_export: true, current_account: current_account)
      PurgeExportJob.perform_async(@iteration.id, current_account.id)
    end

    def factoids
      @factoids = @iteration.factoids.published.order(exported_at: :asc).page(params[:page]).per(30)
      @tab_title = "LokiC :: FactoidType ##{@factoid_type.id} :: Factoids"
    end

    # remove factoids from Limpar, 'articles' table and staging table
    def remove_selected_factoids
      @iteration.update!(purge_export: true, current_account: current_account)
      send_to_action_cable(@factoid_type, @iteration, 'export', 'exported_factoids', 'removing factoids')

      Process.spawn(
        "cd #{Rails.root} && RAILS_ENV=#{Rails.env} "\
        "rake factoid_type:iteration:purge_exported_factoids iteration_id=#{@iteration.id} "\
        "account_id=#{current_account.id} factoid_ids=#{@factoid_ids} &"
      )
    end

    def update_section; end

    private

    def get_factoids
      @factoids  = @iteration.factoids.published.order(exported_at: :asc, id: :asc).page(params[:page]).per(25)
    end

    def get_factoid_ids
      @factoid_ids = params[:factoids_ids]
    end
  end
end

app/views/factoid_types/reviewers_feedback/_form.html.haml
#reviewers_feedback_editor_modal.ml-3
  =form_with(url: factoid_type_fact_checking_doc_reviewers_feedback_index_path(@factoid_type, @factoid_type.fact_checking_doc),
             local: true) do |form|
    .field
      =form.rich_text_area 'reviewers_feedback[body]'
    .mt-3.mb-4
      =form.submit "create feedback", class: 'btn btn-sm btn-outline-dark',
                   onclick: "sessionStorage.removeItem('reviewersFeedback');"
      =form.submit "approve!", class: 'btn btn-sm btn-outline-dark',
                   onclick: "sessionStorage.removeItem('reviewersFeedback');"

  .position-relative
    %hr/
    .label_to_line_modal
      recent feedback

#reviewers_feedback_body_modal

app/views/factoid_types/reviewers_feedback/new.js.erb
(()=>{
    let manual_feedback_modal = $('#manual_feedback_modal')
    let fcd_body = document.getElementById('fcd_body').innerHTML;
    let reviewersFeedback = document.getElementById('reviewers_feedback_body').innerHTML

    document.getElementById('manual_feedback_modal_label').textContent = `<%= "FCD ##{@factoid_type.id} #{@factoid_type.name} -- #{@factoid_type.developer.name} -- reviewers feedback".html_safe %>`
    document.querySelector('#manual_feedback_modal #fcd').innerHTML = fcd_body;
    document.querySelector('#manual_feedback_modal .w-39').innerHTML = `<%= j render 'form' %>`;
    document.querySelector('#reviewers_feedback_body_modal').innerHTML = reviewersFeedback;

    let allFcdLinks = document.querySelectorAll('#manual_feedback_modal #fcd a')
    allFcdLinks.forEach(function(a) {
        a.setAttribute('target', '_blank')
    });

    let samples =
        <% if Rails.env.production? %>
          document.querySelectorAll('#manual_feedback_modal #fcd a[href^="https://lokic.locallabs.com/factoid_types/"][href*="/iterations/"][href*="/samples/"]')
        <% elsif Rails.env.staging? %>
          document.querySelectorAll('#manual_feedback_modal #fcd a[href^="https://lokic-staging.locallabs.com/factoid_types/"][href*="/iterations/"][href*="/samples/"]')
        <% else %>
          document.querySelectorAll('#manual_feedback_modal #fcd a[href^="http://localhost:3000/factoid_types/"][href*="/iterations/"][href*="/samples/"]')
        <% end %>

    samples.forEach(function(a) {
       a.removeAttribute('target');
       a.setAttribute('data-remote', 'true')
    });

    $.FroalaEditor.DefineIcon('submitRF', { NAME: 'check' });
    $.FroalaEditor.RegisterCommand('submitRF', {
        title: 'Submit',
        focus: false,
        undo: false,
        refreshAfterCallback: false,
        callback: function () {
            Rails.ajax({
                type: "PATCH",
                dataType: 'script',
                url: `#{factoid_type_reviewers_feedback_path(@factoid_type)}`,
                data: `reviewers_feedback[body]=${encodeURIComponent(this.html.get())}`
            })
        }
    });

    $.FroalaEditor.DefineIcon('cancelRF', {NAME: 'remove'});
    $.FroalaEditor.RegisterCommand('cancelRF', {
        title: 'Cancel Edit',
        focus: false,
        undo: false,
        refreshAfterCallback: false,
        callback: function () {
            if(confirm('cancel edit reviewers feedback?')) {
                Rails.ajax({
                    type: "GET",
                    dataType: 'script',
                    url: `#{cancel_edit_factoid_type_reviewers_feedback_path(@factoid_type)}`
                })
            }
        }
    });

    let feedbackEditor = $('#reviewers_feedback_editable')
    feedbackEditor.froalaEditor({
        key: 'KfdolbcqsaA2wzA-13==',
        toolbarSticky: true,
        documentReady: true,
        toolbarButtons: ['fullscreen', 'undo', 'redo', '|', '|', 'submitRF', 'cancelRF', '|', '|', 'bold', 'italic', 'underline', 'strikeThrough', 'subscript', 'superscript', '|', 'fontFamily', 'fontSize', 'color', 'inlineClass', 'inlineStyle', 'paragraphStyle', 'lineHeight', '|', 'paragraphFormat', 'align', 'formatOL', 'formatUL', 'outdent', 'indent', 'quote', 'insertLink', 'insertImage', 'insertTable', '|', 'emoticons', 'specialCharacters', 'insertHR', 'selectAll', 'clearFormatting', '|', 'print', 'getPDF', 'help', 'html'],
        imageUploadURL: '/images/upload',
        imageUploadMethod: 'POST',
        saveInterval: 1500,
        saveParam: 'reviewers_feedback[body]',
        saveURL: `${window.location.origin}/factoid_types/#{@factoid_type.id}/reviewers_feedback/autosave`,
        saveMethod: 'PATCH',
        tabSpaces: true
    })

    $(manual_feedback_modal).off('hidden.bs.modal')
    manual_feedback_modal.on('hidden.bs.modal', reviewersFeedbackSaver)
}).call();

function reviewersFeedbackSaver() {
    sessionStorage['reviewersFeedback'] = document.querySelector('#reviewers_feedback_editable .fr-view').innerHTML;
}